/* ----- weread-next mock data ------------------------------------------ */

window.TAG_DEFS = [
  { id: "ai",        name: "AI",          c: "blue",   type: "manual",  count: 142 },
  { id: "history",   name: "历史",        c: "clay",   type: "manual",  count: 318 },
  { id: "scifi",     name: "科幻",        c: "violet", type: "manual",  count: 187 },
  { id: "econ",      name: "经济",        c: "teal",   type: "manual",  count: 96 },
  { id: "lit",       name: "文学",        c: "rose",   type: "manual",  count: 412 },
  { id: "philo",     name: "哲学",        c: "ink",    type: "manual",  count: 73 },
  { id: "biz",       name: "商业",        c: "amber",  type: "manual",  count: 68 },
  { id: "cs",        name: "计算机",      c: "blue",   type: "manual",  count: 124 },
  { id: "wantbuy",   name: "想买",        c: "amber",  type: "manual",  count: 38 },
  { id: "giftable",  name: "可送人",      c: "green",  type: "manual",  count: 27 },
  { id: "classic",   name: "经典",        c: "clay",   type: "manual",  count: 156 },
  { id: "reread",    name: "重读",        c: "teal",   type: "manual",  count: 19 },

  { id: "legacy",    name: "legacy/2018", c: "ink",    type: "imported", count: 2_341, src: "douban.weixin" },
  { id: "legacy-mark", name: "★",         c: "amber",  type: "imported", count: 412, src: "mongo.bookmarks" },

  { id: "paid",      name: "已购",        c: "green",  type: "system",  count: 12_408 },
  { id: "unpaid",    name: "未购",        c: "ink",    type: "system",  count: 77_341 },
  { id: "high",      name: "高分",        c: "green",  type: "system",  count: 3_209 },
  { id: "nocover",   name: "缺封面",      c: "rose",   type: "system",  count: 481 },
  { id: "conflict",  name: "匹配冲突",    c: "rose",   type: "system",  count: 132 },

  { id: "cheap",     name: "便宜",        c: "green",  type: "price",   count: 8_321 },
  { id: "mid",       name: "中等",        c: "ink",    type: "price",   count: 41_092 },
  { id: "exp",       name: "贵",          c: "rose",   type: "price",   count: 1_874 },
  { id: "watch",     name: "重点关注",    c: "amber",  type: "price",   count: 64 },

  { id: "todo-conf", name: "待确认",      c: "amber",  type: "workflow",count: 219 },
  { id: "todo-fill", name: "待补全",      c: "amber",  type: "workflow",count: 481 },
  { id: "todo-buy",  name: "待购买",      c: "amber",  type: "workflow",count: 38 },
  { id: "todo-read", name: "待读",        c: "amber",  type: "workflow",count: 2_104 },
  { id: "archivable",name: "可归档",      c: "ink",    type: "workflow",count: 192 },
];

window.COLLECTIONS = [
  { id: "bl-must",     type: "booklist",  title: "必读清单",     count: 84,  src: "weread", updated: "3 天前" },
  { id: "bl-2024",     type: "booklist",  title: "2024 想读",    count: 56,  src: "weread", updated: "今天" },
  { id: "bl-ai",       type: "booklist",  title: "AI / Agents",  count: 142, src: "weread", updated: "5 天前" },
  { id: "f-stack",     type: "folder",    title: "床头柜",       count: 18,  src: "weread", updated: "今天" },
  { id: "f-tech",      type: "folder",    title: "技术/工具书",   count: 124, src: "weread", updated: "昨天" },
  { id: "arc-old",     type: "archive",   title: "已归档·2019前", count: 2_104, src: "weread", updated: "—" },
  { id: "dir-china",   type: "directory", title: "/Books/中文/历史", count: 318, src: "desktop", updated: "导入于 2021" },
  { id: "dir-cs",      type: "directory", title: "/Books/计算机",    count: 412, src: "desktop", updated: "导入于 2021" },
  { id: "sv-cheap",    type: "saved",     title: "便宜已购待读",   count: 481, src: "saved",   updated: "2 周前" },
  { id: "sv-watch",    type: "saved",     title: "贵+高分+未购",   count: 92,  src: "saved",   updated: "上周" },
  { id: "smart-llm",   type: "smart",     title: "LLM 相关 + 豆瓣 8.5+", count: 47, src: "smart", updated: "实时" },
];

const T = window.TAG_DEFS.reduce((a,t)=>{a[t.id]=t; return a;}, {});

function tag(...ids) { return ids.map(id => T[id]).filter(Boolean); }

// real-ish Chinese book data, mixed categories, varying match/price/state
window.BOOKS = [
  {
    id: "3300198342", weread: "3300198342", douban: "35196328", isbn: "9787208175228",
    title: "置身事内", subtitle: "中国政府与经济发展",
    author: "兰小欢", publisher: "上海人民出版社", category: "经济·中国经济",
    cover: 0,
    price: 41.40, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 219_000,
    weReadRating: 92, doubanRating: 9.1, ratingCount: 41_208,
    progress: 100, readState: "finished", readUpdate: "2025-08-12", shelfUpdate: "2024-11-02",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("econ","classic","high"), marks: ["priority"],
    desc: "理解中国的财政、土地、工业政策与地方政府行为的入门读物，作者用平实语言把宏观与微观连成一条线。",
  },
  {
    id: "3300094652", weread: "3300094652", douban: "1084336", isbn: "9787508647357",
    title: "人类简史", subtitle: "从动物到上帝",
    author: "尤瓦尔·赫拉利", translator: "林俊宏",
    publisher: "中信出版集团", category: "历史·人类学",
    cover: 1,
    price: 38.00, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 380_000,
    weReadRating: 87, doubanRating: 9.1, ratingCount: 247_018,
    progress: 100, readState: "finished", readUpdate: "2024-03-08", shelfUpdate: "2023-01-14",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("history","classic","high","reread"), marks: [],
  },
  {
    id: "3300012871", weread: "3300012871", douban: "26943161", isbn: "9787549620173",
    title: "三体", subtitle: "三体 1",
    author: "刘慈欣", publisher: "重庆出版社", category: "科幻",
    cover: 2,
    price: 25.99, bucket: "mid", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 290_000,
    weReadRating: 95, doubanRating: 9.0, ratingCount: 521_408,
    progress: 100, readState: "finished", readUpdate: "2023-06-18", shelfUpdate: "2022-04-09",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("scifi","classic","high"), marks: [],
  },
  {
    id: "3300224019", weread: "3300224019", douban: null, isbn: null,
    title: "Agents and AI Engineering", subtitle: "Patterns from production systems",
    author: "Chip Huyen", publisher: "O'Reilly", category: "计算机·人工智能",
    cover: 3,
    price: 89.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 410_000,
    weReadRating: 0, doubanRating: 8.7, ratingCount: 412,
    progress: 14, readState: "reading", readUpdate: "今天", shelfUpdate: "上周",
    match: "candidate", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("ai","cs","wantbuy","exp","watch"), marks: ["watch"],
  },
  {
    id: "3300187501", weread: "3300187501", douban: "30259638", isbn: "9787521700091",
    title: "枪炮、病菌与钢铁", subtitle: "人类社会的命运",
    author: "贾雷德·戴蒙德", translator: "谢延光",
    publisher: "上海译文出版社", category: "历史·文明史",
    cover: 4,
    price: 32.50, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 510_000,
    weReadRating: 89, doubanRating: 8.7, ratingCount: 89_318,
    progress: 62, readState: "reading", readUpdate: "3 天前", shelfUpdate: "2024-02-11",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("history","classic","todo-read"), marks: [],
  },
  {
    id: "3300092117", weread: "3300092117", douban: "1052005", isbn: "9787108046789",
    title: "万历十五年",
    author: "黄仁宇", publisher: "三联书店", category: "历史·明史",
    cover: 5,
    price: 0, bucket: "free", paid: true, payType: 3, soldout: 0,
    media: "ebook", words: 188_000,
    weReadRating: 91, doubanRating: 9.0, ratingCount: 351_902,
    progress: 100, readState: "finished", readUpdate: "2022-09-20", shelfUpdate: "2021-10-02",
    match: "confirmed", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("history","classic","legacy"), marks: [],
  },
  {
    id: "3300321118", weread: "3300321118", douban: "36204488", isbn: "9787121478000",
    title: "The Pragmatic Programmer", subtitle: "20th Anniversary Edition",
    author: "David Thomas & Andrew Hunt", translator: "云风",
    publisher: "电子工业出版社", category: "计算机·软件工程",
    cover: 6,
    price: 56.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 280_000,
    weReadRating: 86, doubanRating: 8.6, ratingCount: 8_421,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "5 天前",
    match: "conflict", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("cs","wantbuy","exp"), marks: ["bad","watch"],
    conflicts: ["translator", "cover"],
  },
  {
    id: "3300017244", weread: "3300017244", douban: "3252919", isbn: "9787544253994",
    title: "百年孤独",
    author: "加西亚·马尔克斯", translator: "范晔",
    publisher: "南海出版公司", category: "文学·拉美",
    cover: 7,
    price: 39.50, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 270_000,
    weReadRating: 92, doubanRating: 9.3, ratingCount: 481_209,
    progress: 100, readState: "finished", readUpdate: "2021-04-30", shelfUpdate: "2020-11-08",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("lit","classic","reread","high"), marks: [],
  },
  {
    id: "3300290981", weread: "3300290981", douban: null, isbn: null,
    title: "Designing Data-Intensive Applications", subtitle: "中文版",
    author: "Martin Kleppmann", translator: "冯若航",
    publisher: "中国电力出版社", category: "计算机·分布式系统",
    cover: 1,
    price: 128.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 612_000,
    weReadRating: 0, doubanRating: 9.7, ratingCount: 6_204,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "missing", platforms: { w: true, d: false, j: true, z: false },
    tags: tag("cs","wantbuy","exp","watch","todo-fill"), marks: ["watch","bad"],
  },
  {
    id: "3300034512", weread: "3300034512", douban: "26819726", isbn: "9787544291170",
    title: "局外人",
    author: "阿尔贝·加缪", translator: "柳鸣九",
    publisher: "上海译文出版社", category: "文学·哲学",
    cover: 2,
    price: 9.99, bucket: "cheap", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 92_000,
    weReadRating: 88, doubanRating: 9.1, ratingCount: 142_088,
    progress: 100, readState: "finished", readUpdate: "2024-11-09", shelfUpdate: "2024-10-28",
    match: "confirmed", platforms: { w: true, d: true, j: false, z: true },
    tags: tag("lit","philo","cheap"), marks: [],
  },
  {
    id: "3300401239", weread: "3300401239", douban: null, isbn: "9787521751024",
    title: "数字化转型的迷雾", subtitle: "中国企业的真实路径",
    author: "未知 / 待补全", publisher: "未知",  category: "商业",
    cover: 3,
    price: 48.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 0,
    weReadRating: 0, doubanRating: 0, ratingCount: 0,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "missing", platforms: { w: true, d: false, j: false, z: false },
    tags: tag("biz","todo-fill","nocover"), marks: ["bad"],
    conflicts: ["author","publisher","cover"],
  },
  {
    id: "3300087712", weread: "3300087712", douban: "27036197", isbn: "9787544291309",
    title: "国境以南，太阳以西",
    author: "村上春树", translator: "林少华",
    publisher: "上海译文出版社", category: "文学·日本",
    cover: 4,
    price: 12.00, bucket: "mid", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 150_000,
    weReadRating: 78, doubanRating: 7.9, ratingCount: 89_412,
    progress: 100, readState: "finished", readUpdate: "2020-08-21", shelfUpdate: "2020-06-04",
    match: "imported", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("lit","legacy","legacy-mark"), marks: [],
  },
  {
    id: "album:7820124", weread: "album:7820124", douban: null, isbn: null,
    title: "得到 · 王立铭《行星总动员》",
    author: "王立铭", publisher: "得到", category: "音频·科普",
    cover: 5,
    price: 99.00, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "audiobook", words: 0,
    weReadRating: 88, doubanRating: 0, ratingCount: 0,
    progress: 32, readState: "reading", readUpdate: "上周", shelfUpdate: "2025-03-12",
    match: "missing", platforms: { w: true, d: false, j: false, z: false },
    tags: tag("history","todo-read"), marks: [],
  },
  {
    id: "3300455201", weread: "3300455201", douban: "36504401", isbn: "9787520737000",
    title: "Build", subtitle: "an unorthodox guide to making things worth making",
    author: "Tony Fadell", translator: "刘乙澄",
    publisher: "中信出版集团", category: "商业·产品",
    cover: 6,
    price: 35.00, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 320_000,
    weReadRating: 88, doubanRating: 8.4, ratingCount: 4_182,
    progress: 47, readState: "reading", readUpdate: "今天", shelfUpdate: "2 周前",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("biz","ai"), marks: ["priority"],
  },
  {
    id: "3300521008", weread: "3300521008", douban: "36211983", isbn: null,
    title: "Chip War", subtitle: "The Fight for the World's Most Critical Technology",
    author: "Chris Miller", translator: "蔡承志",
    publisher: "天下文化", category: "历史·科技",
    cover: 7,
    price: 0, bucket: "free", paid: true, payType: 3, soldout: 0,
    media: "ebook", words: 420_000,
    weReadRating: 86, doubanRating: 8.8, ratingCount: 6_021,
    progress: 88, readState: "reading", readUpdate: "昨天", shelfUpdate: "1 月前",
    match: "candidate", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("history","biz","high","todo-conf"), marks: [],
  },
  {
    id: "3300004492", weread: "3300004492", douban: "1083428", isbn: "9787108009067",
    title: "中国哲学简史",
    author: "冯友兰", translator: "赵复三",
    publisher: "三联书店", category: "哲学·中国",
    cover: 0,
    price: 22.50, bucket: "mid", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 350_000,
    weReadRating: 90, doubanRating: 9.2, ratingCount: 28_412,
    progress: 100, readState: "finished", readUpdate: "2023-12-04", shelfUpdate: "2023-09-12",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("philo","classic","legacy"), marks: [],
  },
  {
    id: "3300613371", weread: "3300613371", douban: null, isbn: "9787521767109",
    title: "大模型时代", subtitle: "（待补全）",
    author: "—", publisher: "—", category: "—",
    cover: 1,
    price: 0, bucket: "free", paid: false, payType: 0, soldout: 1,
    media: "unknown", words: 0,
    weReadRating: 0, doubanRating: 0, ratingCount: 0,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "missing", platforms: { w: true, d: false, j: false, z: false },
    tags: tag("ai","todo-fill","nocover"), marks: ["bad"],
    conflicts: ["title","author","cover"],
  },
  {
    id: "3300118842", weread: "3300118842", douban: "26954713", isbn: "9787508692067",
    title: "原则",
    author: "瑞·达利欧", translator: "刘波",
    publisher: "中信出版集团", category: "商业·投资",
    cover: 2,
    price: 49.00, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 480_000,
    weReadRating: 84, doubanRating: 8.4, ratingCount: 56_812,
    progress: 100, readState: "finished", readUpdate: "2022-02-18", shelfUpdate: "2021-08-09",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("biz","legacy","legacy-mark"), marks: [],
  },
  {
    id: "3300882011", weread: "3300882011", douban: "36981203", isbn: null,
    title: "How Big Things Get Done",
    author: "Bent Flyvbjerg", translator: "—",
    publisher: "Currency", category: "商业·项目管理",
    cover: 3,
    price: 78.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 280_000,
    weReadRating: 85, doubanRating: 8.5, ratingCount: 1_204,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "candidate", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("biz","wantbuy","exp","todo-conf"), marks: ["watch"],
  },
  {
    id: "3300204418", weread: "3300204418", douban: "25910874", isbn: "9787108049810",
    title: "城里的房子", subtitle: "豆瓣读书超长书评合集",
    author: "豆瓣", publisher: "—", category: "杂文",
    cover: 4,
    price: 6.99, bucket: "cheap", paid: true, payType: 1, soldout: 0,
    media: "article", words: 88_000,
    weReadRating: 0, doubanRating: 7.6, ratingCount: 218,
    progress: 100, readState: "finished", readUpdate: "2019-05-12", shelfUpdate: "2019-04-08",
    match: "imported", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("lit","legacy","cheap","archivable"), marks: [],
  },
  {
    id: "3300092088", weread: "3300092088", douban: "27598950", isbn: "9787508671772",
    title: "未来简史",
    author: "尤瓦尔·赫拉利", translator: "林俊宏",
    publisher: "中信出版集团", category: "历史·未来",
    cover: 5,
    price: 35.40, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 360_000,
    weReadRating: 84, doubanRating: 8.0, ratingCount: 89_412,
    progress: 100, readState: "finished", readUpdate: "2021-06-04", shelfUpdate: "2021-02-14",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("history","ai"), marks: [],
  },
  {
    id: "3300708221", weread: "3300708221", douban: null, isbn: null,
    title: "Co-Intelligence", subtitle: "Living and Working with AI",
    author: "Ethan Mollick", publisher: "Portfolio", category: "计算机·AI",
    cover: 6,
    price: 65.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 220_000,
    weReadRating: 0, doubanRating: 8.2, ratingCount: 982,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "4 天前",
    match: "candidate", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("ai","cs","wantbuy","todo-conf","exp"), marks: ["watch"],
  },
  {
    id: "3300199101", weread: "3300199101", douban: "27185704", isbn: "9787521711226",
    title: "贫穷的本质",
    author: "阿比吉特·班纳吉, 埃斯特·迪弗洛", translator: "景芳",
    publisher: "中信出版集团", category: "经济·发展",
    cover: 7,
    price: 32.40, bucket: "exp", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 280_000,
    weReadRating: 86, doubanRating: 8.5, ratingCount: 32_018,
    progress: 23, readState: "reading", readUpdate: "2 周前", shelfUpdate: "2024-12-08",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("econ","high","todo-read"), marks: [],
  },
  {
    id: "3300004017", weread: "3300004017", douban: "1003792", isbn: "9787208038271",
    title: "围城",
    author: "钱钟书", publisher: "人民文学出版社", category: "文学·中国",
    cover: 0,
    price: 0, bucket: "free", paid: true, payType: 3, soldout: 0,
    media: "ebook", words: 250_000,
    weReadRating: 93, doubanRating: 9.0, ratingCount: 412_018,
    progress: 100, readState: "finished", readUpdate: "2020-01-12", shelfUpdate: "2019-11-30",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: true },
    tags: tag("lit","classic","legacy"), marks: [],
  },
  {
    id: "3300888412", weread: "3300888412", douban: null, isbn: null,
    title: "The Anxious Generation",
    author: "Jonathan Haidt", publisher: "Penguin Press", category: "社会学",
    cover: 1,
    price: 88.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 320_000,
    weReadRating: 0, doubanRating: 7.9, ratingCount: 514,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "missing", platforms: { w: true, d: true, j: false, z: false },
    tags: tag("biz","wantbuy","todo-conf"), marks: ["watch"],
  },
  {
    id: "3300223091", weread: "3300223091", douban: "30329536", isbn: "9787521714043",
    title: "事实", subtitle: "用数据思考，避免情绪化决策",
    author: "汉斯·罗斯林", translator: "陈仁峰",
    publisher: "文汇出版社", category: "社会·数据",
    cover: 2,
    price: 25.00, bucket: "mid", paid: true, payType: 1, soldout: 0,
    media: "ebook", words: 230_000,
    weReadRating: 86, doubanRating: 8.6, ratingCount: 14_018,
    progress: 100, readState: "finished", readUpdate: "2023-04-18", shelfUpdate: "2022-12-04",
    match: "confirmed", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("econ","biz"), marks: [],
  },
  {
    id: "3300999921", weread: "3300999921", douban: null, isbn: "9787521756019",
    title: "硅谷之火（中文版）",
    author: "保罗·弗赖伯格", translator: "王建华  / 张文",
    publisher: "电子工业出版社", category: "历史·科技",
    cover: 3,
    price: 58.00, bucket: "exp", paid: false, payType: 0, soldout: 0,
    media: "ebook", words: 380_000,
    weReadRating: 0, doubanRating: 8.7, ratingCount: 218,
    progress: 0, readState: "unread", readUpdate: "—", shelfUpdate: "今天",
    match: "review", platforms: { w: true, d: true, j: true, z: false },
    tags: tag("history","cs","wantbuy","todo-conf"), marks: ["bad","watch"],
    conflicts: ["translator"],
  },
];

window.SAVED_VIEWS = [
  { id: "v-all",   title: "全部", count: 89_739,  active: true,  builtin: true },
  { id: "v-now",   title: "在读",  count: 41,    active: false, builtin: true },
  { id: "v-cheap", title: "便宜已购待读", count: 481, active: false, builtin: false },
  { id: "v-watch", title: "贵 + 高分 + 未购", count: 92, active: false, builtin: false },
  { id: "v-ai",    title: "AI / LLM",  count: 142, active: false, builtin: false },
  { id: "v-q",     title: "Data quality 修复队列", count: 219, active: false, builtin: false },
];

window.NAV = [
  { id: "shelf",    label: "Shelf · 书架",     count: 89_739, ic: "shelf",  group: "main" },
  { id: "collections", label: "Collections",  count: 47,     ic: "stack",  group: "main" },
  { id: "tags",     label: "Tags",             count: 312,    ic: "tag",    group: "main" },
  { id: "prices",   label: "Purchases & Price", count: "—",   ic: "yuan",   group: "main" },
  { id: "matches",  label: "Douban Matches",   count: 1_204,  ic: "link",   group: "main" },
  { id: "platforms",label: "Platforms",        count: 4,      ic: "globe",  group: "main" },
  { id: "notes",    label: "Notes",            count: 2_104,  ic: "note",   group: "main" },

  { id: "quality",  label: "Data Quality",     count: 613,    ic: "warn",   group: "ops" },
  { id: "sync",     label: "Sync Runs",        count: 28,     ic: "sync",   group: "ops" },
  { id: "chat",     label: "Chat",             count: "·",    ic: "chat",   group: "ops" },
];
